### ISSUE TITLE
Multipple entries in devices.h

### ISSUE THREAD

**Issue by wissting** [vdudouyt/minipro#22]
Hi
I have a ST M27C256B DIP eprom, I can successfully read and write it from MiniPro V6.00 in wine but fail to read it with minipro:

% ./minipro -p "M27C256B @DIP28" -c code -w test3
Found Minipro TL866A v3.62.2
Chip ID OK: 0x208d
Couldn't open file: No such file or directory

There are multiple entries in devices.h of '.name = "M27C256B @DIP28"', that whould be the ST and SGS versions? Is there a way to specify brand?

Thanks for the utility btw! :)

**Comment by chenz** [comment]
The two entries for "M27C256B @DIP28" in devices.h are completely identical. This is also true for others (for example "M27C4002 @DIP40"). 

Since the name is the only way to specify the device, it should be unique. But it is not - `minipro -l | sort | uniq -d` produces 1592 non-unique device names.

Maybe a problem with the conversion tools used to produce devices.h.

**Comment by DavidGriffith** [comment]
Duplicate #64
