### ISSUE TITLE
Reading fuses over icsp error

### ISSUE THREAD

**Issue by z-op** [vdudouyt/minipro#23]
minipro -i -p "ATMEGA8L" -c config -r atmega8l.fuses
Found Minipro TL866A v3.63.2
Chip ID OK: 0x1e9307
Reading fuses... IO error: expected 10 bytes but 9 bytes transferred.

**Comment by z-op** [comment]
minipro -i -p "atmega16a" -c config -r atmega16a.fuses
Found Minipro TL866A v3.63.2
IO error: expected 8 bytes but 5 bytes transferred

same with atmega32

**Comment by danilorcesar** [comment]
Hi,

I have the following error message:

minipro -p W25Q16BV -r teste.bin
Found Minipro TL866A v3.72.2
IO error: expected 8 bytes but 5 bytes transferred

Can you help me?
Regards,

**Comment by DavidBuchanan314** [comment]
I'm having a similar issue. Is it related?

```
$ minipro -p 'MX25L6406E @SOP8' -r ofw.bin
Warning: firmware is too old
Found Minipro TL866CS v3.58.2
IO error: expected 8 bytes but 5 bytes transferred
```

**Comment by elosha** [comment]
Could be caused by potentially buggy programmer information in our devices.h. If so, it would cause a difference between the number of fuse bytes we expect (correct) and what we instruct the programmer to deliver (incorrect, but also intransparent).

Evidence: Similar issue existed in the original Windows tool until 2015-06-12, changelog of version 6.16:
> Fix：some ATMEGA8 Fuse bits Program

In this case, one would need to extract updated device info from a recent Windows tool. (Where did devices.h originally came from?)

**Comment by DavidGriffith** [comment]
@elosha I just now emailed @vdudouyt asking where devices.h came from.

**Comment by chenz** [comment]
The device database must have been reverse engineered from InfoIC.dll from the windows software. I have also been looking into it. One cannot read the tables straight from the dll though, because parts of them are populated by code at runtime. I think it might be easiest to write a small windows tool that loads the dll and dumps the tables.

More info here: http://www.nullsecurity.org/article/minipro_reverse_engineering_the_infoic_dll (see the comments - they dumped the populated tables from a memory snapshot taken in a debugger).
