### ISSUE TITLE
Build from github, crlf error

### ISSUE THREAD

**Issue by z-op** [vdudouyt/minipro#24]
fakeroot dpkg-buildpackage -b
dpkg-buildpackage: пакет исходных текстов minipro
dpkg-buildpackage: версия исходных текстов 0.1-1
dpkg-buildpackage: source distribution unstable
dpkg-buildpackage: исходные тексты изменены minoru minoru@unknown
dpkg-buildpackage: архитектура узла i386
 dpkg-source --before-build minipro
»pkg-source: ошибка: неправильное поле Format «3.0 (quilt)
dpkg-buildpackage: ошибка: dpkg-source --before-build minipro возвратил код ошибки 25

after this command all builds fine:
find ./ -type f -exec dos2unix {} \;

**Comment by DavidGriffith** [comment]
I don't see any CR LF problems.

**Comment by DavidGriffith** [comment]
Got a fix coming for this.

**Comment by DavidGriffith** [comment]
Could we close this now?

**Comment by vdudouyt** [comment]
I don't think so, as 'dpkg-buildpackage' is now broken by #455dd. Because $DESTDIR is something on what does the Debian packaging system relies.

Could you please let me know how it comes that you decided to replace it with $PREFIX? I'm asking because we need to deploy a build system which is suitable for all UNIX-like platforms.

Best Regards,
Valentin

**Comment by DavidGriffith** [comment]
I used $PREFIX because that's the convention I've always seen in hand-built Makefiles.  You seem to have a lot of stuff in the debian/ directory that probably doesn't need to be there.  I don't see how $DESTDIR is depended upon in there, but I'm not at my peak coding condition right now.  The work I did on Minipro's Makefile is very similar to how I wrote the Makefile for Frotz (https://github.com/DavidGriffith/frotz).  You'll note that the dist target is identical.  Frotz's Debian package is very simple and I'm positive that it can be pressed into service for Minipro with very little trouble.  I'll work on it this weekend and show you something by Monday.

**Comment by vdudouyt** [comment]
Thank you very much! Please check out the new 'cmake' branch, by the way.

Best Regards,

Valentin

**Comment by z-op** [comment]
same problem with miniprohex script

**Comment by z-op** [comment]
In the master branch has another problem, after correct line endings i try to build package with:
fakeroot dpkg-buildpackage -b

builds was filed because starts installation:
   dh_auto_test
 debian/rules binary
dh binary 
   dh_testroot
   dh_prep
   dh_auto_install
make[1]: Вход в каталог `/home/felis/minipro'
mkdir -p /usr/local/bin/
mkdir -p /etc/udev/rules.d/
mkdir -p /usr/local/share/man/man1/
mkdir -p /etc/bash_completion.d/
cp minipro /usr/local/bin/
cp: невозможно создать обычный файл «/usr/local/bin/minipro»: Отказано в доступе
make[1]: *** [install] Ошибка 1
make[1]: Выход из каталога `/home/felis/minipro'
dh_auto_install: make -j1 install DESTDIR=/home/felis/minipro/debian/minipro AM_UPDATE_INFO_DIR=no returned exit code 2
make: *** [binary] Ошибка 2
dpkg-buildpackage: ошибка: debian/rules binary возвратил код ошибки 2

**Comment by DavidGriffith** [comment]
I don't think this is a problem anymore.  Please let me know if I'm wrong.
